---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7.0

suites:
  - name: magic
    run_list:
      - recipe[app_deploy-test::magic]
    attributes:
